### ISSUE TITLE
How use configure using Cloud Storage instead of Physical path location

### ISSUE THREAD

**Issue by tangkhaiphuong** [gordon-matt/peachpie-responsive-file-manager#3]
How to configure this package can integrating with Cloud Object storage such as Mino or Google Cloud Storage

**Comment by gordon-matt** [comment]
Hi,

This project is using a third party library: "Responsive File Manager", which you can find here:
https://www.responsivefilemanager.com/

First you will need to find out if this library supports cloud storage. I'm not sure, because I have never had the requirement for cloud storage in my projects. Anyway, if the file manager does support cloud storage, then probably it will be something you need to modify in the config file. You will need to do this:

1. Fork this project.

2. Modify *\Website\filemanager\config\config.php*. For example, look at line #75. There you can see I am passing in some settings to the config file.

3. Pass the new appsettings in the web application. Go to *WebApplication\Startup.cs* and look at line #82. Then you should be able to understand what to do.

However, if the "Responsive File Manager" library does not support cloud storage, then unfortunately I cannot help you. You will need to open a request on a different GitHub repo, which you can find here:
https://github.com/trippo/ResponsiveFilemanager

If you are able to implement this in your fork, you can create a pull request and I will be able to merge your changes into my code and then release a new NuGet package for it.

Good luck.
