### ISSUE TITLE
Conflict with SixLabors.ImageSharp 2.0.0+ 

### ISSUE THREAD

**Issue by endorbilisim** [gordon-matt/peachpie-responsive-file-manager#31]
I installed nuget to my CMS project but constantly getting "Unexpected end of JSON input" error. (Images are saved but thumbs are not) After examining the project in detail, if I use version SixLabors.ImageSharp 2.0.0 or higher in my app, I get the error "Unexpected end of JSON input". Using SixLabors.ImageSharp 1.0.4 fixes this issue but using older version does more harm than good.

**Comment by gordon-matt** [comment]
New version released for .NET 8 with all packages updated.

**EDIT**: The ImageSharp library is still old, but it's unrelated to this project. As discussed in #32 , the problem is with the PeachPie dependency:
![image](https://github.com/gordon-matt/peachpie-responsive-file-manager/assets/2860937/a0992073-35c5-4523-bc23-f90eeb6b7a4d)

Please raise a task with them to update the library: https://github.com/peachpiecompiler/peachpie
