### ISSUE TITLE
ImageSharp version update request

### ISSUE THREAD

**Issue by endorbilisim** [gordon-matt/peachpie-responsive-file-manager#34]
There is a high vulnerability problem with ImageSharp versions lower than 2.1.7 (https://github.com/advisories/GHSA-65x7-c272-7g7r). Can you please update your version?

**Comment by gordon-matt** [comment]
All packages have been updated and a new version released.

**EDIT**: The ImageSharp library is still old, but it's unrelated to this project. As discussed in #32 , the problem is with the PeachPie dependency:
![image](https://github.com/gordon-matt/peachpie-responsive-file-manager/assets/2860937/a0992073-35c5-4523-bc23-f90eeb6b7a4d)

Please raise a task with them to update the library: https://github.com/peachpiecompiler/peachpie
